### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by kaktus42** [pachyderm/python-pachyderm#17]
Hi there.
Am I correct that no authentication method is implemented here?

**Comment by ysimonson** [comment]
It's available as raw protobuf objects now. Not the prettiest but it should work.

**Comment by sebinsua** [comment]
@ysimonson When you say "not the prettiest", what do you mean?

How do we authenticate programmatically?

**Comment by ysimonson** [comment]
@sebinsua I was wrong; I thought auth was implemented as gRPC endpoints, but it's handled via metadata. You still could authenticate using this library, but you'd have to set gRPC metadata yourself. Having not done so myself, I'm not sure how much trouble it is - but either way, it seems like a good thing to add to this library.

**Comment by ysimonson** [comment]
Support for auth is on master and will go out with the next release. In order to use it, you need to grab a token in an auth-enabled cluster via `pachctl auth get-auth-token`, then either pass it in as a parameter like so: `client = python_pachyderm.PfsClient(auth_token="...")`, or set the environment variable `PACH_PYTHON_AUTH_TOKEN`.
